### ISSUE TITLE
There was an error @ Line: Func: chk_sign Signature invalid. Exiting. Exiting with status code 1

### ISSUE THREAD

**Issue by AlbertRAR** [mtompkins/linux-kernel-utilities#2]
Hi, @mtompkins.  While running ./compile_linux_kernel.sh, after downloading kernel, script stops with error:
"There was an error @ Line: Func: chk_sign Signature invalid. Exiting. Exiting with status code 1"
How to fix it? And why tghis error occurs? Thanks

**Comment by mtompkins** [comment]
Hi @AlbertRAR 

This means the download failed the GPG signature check. It may have been a download problem or the signature that is on file for the package author on the GPG servers. If the signature can't be confirmed it exits for your protection.

The first thing to do is to simply try again. Also let me know which kernel you are trying to compile and I'll give it a test on my end to make sure it is all working correctly.

**Comment by AlbertRAR** [comment]
Thanks for fast response. I tried to compile latest kernel with "./compile_linux_kernel.sh latest" command, and then with manual choosing kernel command, both ended with same "Signature invalid" message. After that i downloaded kernel manual from kernel.org and ran with it, and succesfully completed compilation)

**Comment by mtompkins** [comment]
OK - 

Not surprised you could download the kernel file directly and compile. That is the expected behavior.
There is also a signature file for each archive that is used to check against the package. That is what is failing. After the error window returns you to a command prompt, would it be possible to see a screen shot? (http://picpaste.com/) That would be helpful in making sure we are literally looking at the same moment.

I'll spin up a VM and try the `latest` option and we will compare our results.

**Comment by AlbertRAR** [comment]
Btw, when scipt downloaded kernel with first 2 attempts, i noticed that downloaded file with kernel was containing non latin charactes, maybe it matters

**Comment by mtompkins** [comment]
That is interesting / peculiar. The download should have a simple name of kenerl_ appended with date and time. There shouldn't be any curious characters. If not the case for you, it may be your UTF settings. If I might see a screenshot of the folder with those curious characters that would be helpful. It is likely that is in play. If it can't find the signature file because of a character translation everything after that would indeed fail.

Below you'll see the two files correctly named from the download.

![screenshot from 2016-07-17 10-04-25](https://cloud.githubusercontent.com/assets/4105910/16901066/5375737a-4c06-11e6-862a-a1e01a41b5be.png)

**Comment by mtompkins** [comment]
The script does continue gracefully in my tests so it is likely the issue you mentioned (characters from the download). This can be a result of your shell settings.

You can try `export LC_ALL=C` in a new shell before running the scripts to see if that solves it for your specific environment.

**Comment by AlbertRAR** [comment]
My utf locale settings different from english, so in the folder name  "Jul" was translated to my local language

**Comment by mtompkins** [comment]
Perfect; so indeed the cause. What you can do to help automate it for yourself is use one of the profiles. This will allow you to add a line at the very top to export the necessary settings. The `zeus` profile is just an example of how to set up such a profile.

**Comment by AlbertRAR** [comment]
Ok, Thanks!
