### ISSUE TITLE
Makefile:546: recipe for target 'xconfig' failed

### ISSUE THREAD

**Issue by kattak2k** [mtompkins/linux-kernel-utilities#9]
when I tried compiling "./compile_linux_kernel.sh --latest" , I am getting the error "Makefile:546: recipe for target 'xconfig' failed"
I don't understand what went wrong.

Please check and revert

**Comment by mtompkins** [comment]
That's caused (most likely) by a missing dependency.
While the script does try to confirm needed packages are installed, it seems one has been missed.

So .... let's start with which distro and version?

**Comment by kattak2k** [comment]
Thank you for very quick response,  I am on ubuntu 16.10

**Comment by mtompkins** [comment]
OK - if you can give me a screenshot, that would be helpful.
It's likely the QT package.

**Comment by mtompkins** [comment]
Also let me know the output from:
```
qmake -v
```

**Comment by kattak2k** [comment]
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

**Comment by mtompkins** [comment]
OK - so that confirms the missing dependencies. I'll have to try and reproduce the reason why it is missing the install.

You can install it manually with:
```
sudo apt-get -y install qt5-default
```

If you would do that and then advise where you are - if that resolves.

**Comment by kattak2k** [comment]
After the execute the command. I am facing some other issue...  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt5-default : Depends: qtbase5-dev
E: Unable to correct problems, you have held broken packages.

**Comment by mtompkins** [comment]
Ok, that's helpful and explains what is occurring - the script is unable to install the QT dependency because you have some broken packages. Once that condition is sorted the dependencies should install properly.

You'll have to identify what is causing that help package condition and remove / reinstall / or otherwise address it. Unfortunately this isn't an area I can really help you with ...

However, in my own experience, I have found Synaptic package manager helpful in resolving these sorts of issues. You can also do a search on askubuntu.com for various ways of dealing with it through apt / dpkg, etc.

**Comment by kattak2k** [comment]
Thank you, I will try fixing with synaptic. I am afraid i might not do something wrong with synaptic. One final question , can I install everything that I find red in synaptic?

**Comment by mtompkins** [comment]
If you are unfamiliar with the tool, no I would not use it.
I would do some research on the askubuntu forum and try to learn / understand about held packages.

Synaptic's interface has a filter to show what's held - but that does not mean that you should "simply" uninstall what it shows you. You'll likely need a little hand holding if this is the first time you've delt with held packages and the Ubuntu forums are the place to get that help.

**Comment by kattak2k** [comment]
Thank you

**Comment by mtompkins** [comment]
I just want to leave a little bit of unsolicited advice. This isn't meant to be harsh nor critical but helpful.
If you haven't a need to otherwise alter the kernel

- You should probably stick with the script that simply updates the Ubuntu kernel. You don't gain anything by compiling it yourself if no changes are to be made. 

It is, of course, interesting to learn and explore how these things go together with each other and how a kernel is compiled and I fully endorse your bravery in trying to go down that road. If you want to experiment you should first spin up a VM (like Virtualbox) on your Ubuntu machine so you do not put your system at risk. 

In the VM you can bang away, compile the kernel - try everything and make sure outcomes are as expected before you do anything with you "main" system.
